### ISSUE TITLE
Password 

### ISSUE THREAD

**Issue by Siianko12** [wandersonca/HPC-Password-Cracker#27]
Hello, I can't find your password to download libssl-dev package. Could you write it to me?

**Comment by wandersonca** [comment]
I assume you figured it out @Siianko12 .

You just need to install that package in your operating system. Notes it the README: https://github.com/wandersonca/HPC-Password-Cracker#compilation-notes

**Comment by wandersonca** [comment]
If you have any enhancements, send me a pull request.
